
use_agent_config: False

environment:  
  env_type: general
    
  time_configs:
    start_edge: 1000
    edge_delta: 50
    end_edge: 5000
    update_method: edge

  managers:
  
    general:
      model_config_name: llama3
      dataset_name: sephora
      embedding_model_name: all-MiniLM-L6-v2
      general_memory_config:
        reflect_memory: False
        memory_retrieval_method: random_walk
        memory_retrieval_params:
          walk_length: 3
          num_walks: 10
        memory_context_length: 1000
      graph_structure: 
        node: ["sephora_author", "sephora_product"]
        edge: ["sephora_review"]
        item_nodes: ["sephora_product"]
        actor_nodes: ["sephora_author"]

      retriever_kwargs: 
        type: graph_general_vector_retriever
        search_kwargs:
          k: 20
          

  agent:
    type: general_agent
    llm:
      config_name: llama3
    long_memory:
      type: general_memory

