environment:
  
  env_type: social


  time_configs:
    start_time: 2024-04-12
    cur_time: 2024-04-12
    end_time: 2024-04-28
    social_time_delta: 1
    people_add_delta: 1

  social_configs:
    max_people: 100000
    add_people_rate: 0.00025
    delete_people_rate: 0.00025

  managers:
    social:
      social_data_dir: data/systhetic
      data_name: twitter_large_1e6
      generated_data_dir: data/generated

      control_profile:
        hub_rate: 0.2

      tool_kwargs:
        filter_keys: ["follow", "big_name", "topic"]
        hub_connect: True
      
      retriever_kwargs:
        type: graph_vector_retriever
        search_kwargs:
          k: 20

  agent:
    type: social_agent
    llm:
      config_name: llama3
    memory:
      type: action_memory

use_agent_config: false